#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)
library(tidyverse)
library(shinyalert)
score = 0
load('samples')

load('g')


samples = samples %>% filter(!is.na(text)) %>% filter(text != ' ') %>% filter(text != '')

# Define UI for application that draws a histogram
ui <- fluidPage(useShinyalert(),

    # Application title
    titlePanel("Real or False News?"),
    

    # Sidebar with a slider input for number of bins 
    sidebarLayout(sidebarPanel(p("Can you tell the difference between real abstracts from the Calendar of State Papers, and those generated by GPT-2?"), br(),p("Generate a pair of abstracts, then select your choice."), p("Tweet me funny ones <a href = 'https://twitter.com/lievesofgrass'>@lievesofgrass</a>" %>% HTML()) ,
        actionButton('generate', 'Generate False Newes'), br(), br(),
        selectInput('which', 'Which is False?', choices = c(1,2)),
        actionButton('check', 'Check'),
        htmlOutput("answertext"),
        br(),
        htmlOutput("score")
        
        ),

        # Show a plot of the generated distribution
        mainPanel(
           htmlOutput("distPlot")
  
        )
    )
)

# Define server logic required to draw a histogram
server <- function(input, output, session) {

text_fake = eventReactive(input$generate,{
    
    samples %>% sample_n(1) %>% pull(text)
})

text_real = eventReactive(input$generate,{
    
    g %>% sample_n(1) %>% pull(value)
})

a = reactive({sample(c(text_real(), text_fake())) 
    
})

output$distPlot = renderText({
    
    print(a()[1])
    
  paste0("<b>1)</b><br>", a()[1], "<br><br>_______________________<br><br>","<b>2)</b><br>", a()[2]) %>% 
        HTML()
    
    
    

    
})

answer = observeEvent(input$check, {
    
    
    if(a()[as.numeric(input$which)] == text_fake()){
        
        shinyalert("Correct!", "You found the fake - well done!", type = "success")   
        
        } else{ 
            
            shinyalert("Oops!", "No, that one was real!", type = "error")
            
            }
    

    
})




rv <- reactiveValues(
    round = 0,
    score = 0

)

observeEvent(input$check,{
    
    rv$round = rv$round+1
    
    if(a()[as.numeric(input$which)] == text_fake()){
        
        rv$score = rv$score + 1 }
        

        
        print(rv$score)
        print(rv$round)
})

output$score = renderText({
    
    paste("<p><b>Correct:</b>",rv$score, "<p><b>Total:</b>",rv$round)
})


    
    
    






    
}

# Run the application 
shinyApp(ui = ui, server = server)
